# Generated by Django 4.2.9 on 2026-04-24 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThrottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Email Throttle',
                'verbose_name_plural': 'Email Throttles',
            },
        ),
        migrations.CreateModel(
            name='UsedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Used Token',
                'verbose_name_plural': 'Used Tokens',
                'indexes': [models.Index(fields=['user_id'], name='accounts_us_user_id_d64e84_idx')],
            },
        ),
    ]
